spring.application.name=quanlichitieu

# Cấu hình kết nối H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cho phép sử dụng giao diện quản lý /h2-console trên trình duyệt
spring.h2.console.enabled=true

# Cấu hình Hibernate tự động tạo bảng dựa trên class JPA Entity của bạn
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
server.port=2222
