spring.application.name=quanlichitieu

# Cấu hình kết nối H2 Database
# 1. Cấu hình kết nối MySQL sử dụng biến môi trường từ Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# 2. Cấu hình Hibernate cho MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=2222
